/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   url-detailed-editor.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

import {UrlDetailedEditor} from './src/UrlDetailedEditor.js';
